# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComboRcpp <- function(Rn, Rr, Rv, Rrep, fun1, fun2, lim, numRow) {
    .Call('algos_ComboRcpp', PACKAGE = 'algos', Rn, Rr, Rv, Rrep, fun1, fun2, lim, numRow)
}

NumFactorsSieve <- function(n) {
    .Call('algos_NumFactorsSieve', PACKAGE = 'algos', n)
}

PrimeFactorizationListRcpp <- function(n) {
    .Call('algos_PrimeFactorizationListRcpp', PACKAGE = 'algos', n)
}

EulerPhiSieveRcpp <- function(n) {
    .Call('algos_EulerPhiSieveRcpp', PACKAGE = 'algos', n)
}

EratosthenesRcpp <- function(Rb1, Rb2) {
    .Call('algos_EratosthenesRcpp', PACKAGE = 'algos', Rb1, Rb2)
}

